name: app_http_client
description: A simple Dio HTTP client wrapper with simple, predictable errors.
version: 2.0.0

environment:
  sdk: '^3.2.0'

dependencies:
  dio: ^5.0.0

dev_dependencies:
  mocktail: ^0.1.4
  test: ^1.16.0
  very_good_analysis: ^2.1.2
